name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Personal Metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: maulanasyaa
          template: classic
          base: header
          config_timezone: Asia/Jakarta
          
          # Isocalendar 3D (kalender kontribusi tahunan)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          config_padding: 0, 2 + 8%
